### ISSUE TITLE
Blocking requests calls

### ISSUE THREAD

**Issue by Fuyukai** [Aurorastation/BOREALISbot2#6]
Your bot appears to be doing a lot of HTTP calls using the Requests library.

Because asyncio, these are bad, and will block the entire event loop. 

You should be using aiohttp for these requests (http://aiohttp.readthedocs.io/en/stable/)

**Comment by skull132** [comment]
Thank you for the heads up, will look into it whenever I get a chance and will refractor.

**Comment by skull132** [comment]
\> 2 years later

Well at least it's done now.

**Comment by Fuyukai** [comment]
Not quite 2 years, but still.
